//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albums
    {
        public int id { get; set; }
        public string AlbumName { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public Nullable<int> GenreID { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
